<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\..\Railway.Application\Railway.Application.csproj" />
    <ProjectReference Include="..\..\Railway.Contracts\Railway.Contracts.csproj" />
    <ProjectReference Include="..\..\Railway.Messaging\Railway.Messaging.csproj" />
    <ProjectReference Include="..\..\Railway.Persistence\Railway.Persistence.csproj" />
  </ItemGroup>
</Project>
